### ISSUE TITLE
Suggestion: Try to stay consistent with the CSS code formatting as well.

### ISSUE THREAD

**Issue by josephtkim** [RajShah6262/prj-rev-bwfs-tea-cozy#6]
Always try to stay consistent with code formatting in every language you work with. This is a very important concept in code design because following a structure of code writing throughout the code makes it visually better to read for others, making it easier to work with and understand. For example, on these lines in your CSS, you might make the formatting more consistent, like using 1 empty space between selectors, always indenting each property, and not leaving any empty lines in a selector. Like so, for these lines

https://github.com/RajShah6262/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/Resources/Css/style.css#L1-L43

```css
body {
  font-family: helvetica;
  font-size: 22px;
  color: seashell;
  opacity: 0.9;
  background-color: black;
}

.header {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  height: 69px;
  position: fixed;
  top: 0px;
  left: 0px;
  width: 100%;
  z-index: 5;
  background-color: black;
  border-bottom: 1px solid seashell;
  justify-content: space-between;
}

.logo{
  margin-left: 10px;
}

a {
  color: white;
}

.nav {
  display: inline-block;
  margin-right: 10px;
}

.nav span {
  margin: 0 10px;
}
```
